# Generated by Django 4.2.3 on 2023-07-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='url_video',
            field=models.CharField(default='', max_length=50, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
